import type { CSSProperties } from "react";

export const indexDetailsStyles = {
  root: {
    background: "var(--white)",
    borderTop: "1px solid var(--border-card)",
    boxSizing: "border-box",
    overflow: "visible",
  },
  trigger: {
    alignItems: "center",
    background: "transparent",
    border: 0,
    borderRadius: 0,
    boxShadow: "none",
    color: "var(--title-ink)",
    cursor: "pointer",
    display: "grid",
    font: "inherit",
    fontWeight: 700,
    gridTemplateColumns: "1fr auto",
    minHeight: "2.75rem",
    padding: "0.75rem 0.5rem",
    textAlign: "left",
    transform: "none",
    width: "100%",
  },
  content: {
    display: "grid",
    gap: "0.5rem",
    padding: "0 0.5rem 0.75rem",
  },
  quote: {
    alignItems: "start",
    gridTemplateColumns: "minmax(0, 1fr) minmax(0, 7rem)",
    background: "var(--white)",
    border: 0,
    boxSizing: "border-box",
    display: "grid",
    gap: "0.55rem",
    margin: 0,
    minInlineSize: 0,
    padding: 0,
  },
  source: {
    background: "var(--white)",
    border: "1px solid var(--border-card)",
    borderRadius: "var(--radius-control)",
    boxSizing: "border-box",
    color: "var(--title-ink)",
    lineHeight: 1.4,
    minHeight: "3.6rem",
    minWidth: 0,
    padding: "0.5rem",
    resize: "vertical",
    width: "100%",
  },
} satisfies Record<string, CSSProperties>;
