import type { CSSProperties } from "react";

export const pageSegmentsStyles = {
  root: {
    alignItems: "stretch",
    boxSizing: "border-box",
    color: "var(--text-main, #1f2937)",
    display: "flex",
    flexDirection: "column",
    gap: "1rem",
    height: "auto",
    justifyContent: "flex-start",
    margin: "0 auto",
    maxWidth: "42rem",
    maxHeight: "100%",
    minHeight: 0,
    overflowY: "auto",
    padding: "1rem 1rem 5rem",
    width: "100%",
  },
  title: {
    color: "#0f172a",
    fontSize: "1.75rem",
    fontWeight: 700,
    lineHeight: 1.15,
    margin: 0,
  },
  blankRow: {
    alignItems: "center",
    color: "var(--text-main, #1f2937)",
    cursor: "pointer",
    display: "flex",
    fontSize: "0.95rem",
    gap: "0.55rem",
    padding: "0.85rem 1rem 1rem",
  },
  checkboxIndicator: {
    alignItems: "center",
    display: "flex",
    justifyContent: "center",
  },
  checkboxRoot(disabled: boolean): CSSProperties {
    return {
      alignItems: "center",
      background: disabled ? "#f3f4f6" : "#ffffff",
      border: "1px solid rgba(15, 23, 42, 0.35)",
      borderRadius: "0.25rem",
      color: "var(--primary-color-light, #008ba3)",
      cursor: disabled ? "not-allowed" : "pointer",
      display: "inline-flex",
      flex: "0 0 auto",
      height: "1rem",
      justifyContent: "center",
      opacity: disabled ? 0.65 : 1,
      padding: 0,
      width: "1rem",
    };
  },
  sectionTitle: {
    color: "var(--text-muted, #4b5563)",
    display: "inline-flex",
    fontSize: "0.85rem",
    fontWeight: 700,
    letterSpacing: 0,
    padding: "0 1rem",
  },
  grid: {
    display: "grid",
    gap: "0.75rem",
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    padding: "0 1rem 1rem",
  },
  item: {
    alignItems: "center",
    background: "#ffffff",
    border: "0.0625rem solid rgba(15, 23, 42, 0.12)",
    borderRadius: "0.5rem",
    boxSizing: "border-box",
    display: "flex",
    gap: "0.55rem",
    padding: "0.6rem 0.75rem",
  },
  itemText(disabled: boolean): CSSProperties {
    return {
      color: disabled ? "var(--text-muted, #9ca3af)" : "var(--text-main, #1f2937)",
      fontSize: "0.92rem",
    };
  },
  message(variant: "error" | "success"): CSSProperties {
    return {
      background: variant === "error" ? "#fdecea" : "#edf6ff",
      borderRadius: "0.625rem",
      color: variant === "error" ? "#7a1c1c" : "#1f2937",
      display: "block",
      font: "500 0.875rem/1.45 var(--font-family, system-ui)",
      padding: "0.625rem 0.75rem",
      textAlign: "left",
    };
  },
  footer: {
    alignItems: "center",
    background: "#ffffff",
    borderTop: "1px solid rgba(0,0,0,0.08)",
    bottom: "5rem",
    display: "flex",
    flex: "0 0 auto",
    flexWrap: "wrap",
    gap: "0.5rem",
    justifyContent: "center",
    marginTop: 0,
    paddingTop: "0.75rem",
    position: "sticky",
    scrollMarginBottom: "6rem",
    zIndex: 2,
  },
  button(variant: "primary" | "secondary"): CSSProperties {
    return {
      alignItems: "center",
      backgroundColor: variant === "secondary" ? "var(--background-color-light, #fff)" : "var(--primary-color-light, #008ba3)",
      border: variant === "secondary" ? "1px solid rgba(0,0,0,0.12)" : "1px solid var(--primary-color-light, #008ba3)",
      borderRadius: "0.5rem",
      boxShadow: variant === "secondary" ? "0 0.05rem 0.15rem rgba(0,0,0,0.04)" : "0 0.1rem 0.25rem rgba(0,0,0,0.08)",
      color: variant === "secondary" ? "var(--text-main, #0f172a)" : "var(--background-color-light, #fff)",
      cursor: "pointer",
      display: "inline-flex",
      fontWeight: 600,
      height: "2.5rem",
      justifyContent: "center",
      minWidth: "7rem",
      outline: "none",
      padding: ".5rem 1rem",
      position: "relative",
      scrollMarginBottom: "6rem",
      textAlign: "center",
      userSelect: "none",
      whiteSpace: "nowrap",
    };
  },
} satisfies Record<string, CSSProperties | ((...args: never[]) => CSSProperties)>;
