import type { CSSProperties } from "react";

export const pageSegmentsStyles = {
  root: {
    alignItems: "stretch",
    boxSizing: "border-box",
    color: "var(--title-ink)",
    display: "flex",
    flexDirection: "column",
    gap: "1rem",
    height: "auto",
    justifyContent: "flex-start",
    width: "100%",
  },
  title: {
    color: "var(--title-ink)",
    fontSize: "var(--panel-title-size)",
    fontWeight: "var(--panel-title-weight)",
    letterSpacing: "var(--panel-title-tracking)",
    lineHeight: "var(--panel-title-line-height)",
    margin: 0,
  },
  blankRow: {
    alignItems: "center",
    color: "var(--title-ink)",
    cursor: "pointer",
    display: "flex",
    fontSize: "0.95rem",
    gap: "0.55rem",
    padding: "0.85rem 1rem 1rem",
  },
  checkboxIndicator: {
    alignItems: "center",
    display: "flex",
    justifyContent: "center",
  },
  checkboxRoot(disabled: boolean): CSSProperties {
    return {
      alignItems: "center",
      background: disabled ? "var(--gray-100)" : "var(--white)",
      border: "1px solid var(--border-card)",
      borderRadius: "var(--radius-control)",
      color: "var(--primary)",
      cursor: disabled ? "not-allowed" : "pointer",
      display: "inline-flex",
      flex: "0 0 auto",
      height: "1rem",
      justifyContent: "center",
      opacity: disabled ? 0.65 : 1,
      padding: 0,
      width: "1rem",
    };
  },
  sectionTitle: {
    color: "var(--slate-500)",
    display: "inline-flex",
    fontSize: "0.85rem",
    fontWeight: 700,
    letterSpacing: 0,
    padding: "0 1rem",
  },
  grid: {
    display: "grid",
    gap: "0.75rem",
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    padding: "0 1rem 1rem",
  },
  item: {
    alignItems: "center",
    background: "var(--white)",
    border: "1px solid var(--border-card)",
    borderRadius: "var(--radius-card)",
    boxSizing: "border-box",
    display: "flex",
    gap: "0.55rem",
    padding: "0.6rem 0.75rem",
  },
  itemText(disabled: boolean): CSSProperties {
    return {
      color: disabled ? "var(--slate-500)" : "var(--title-ink)",
      fontSize: "0.92rem",
    };
  },
  message: {
    background: "#FEF2F2",
    borderRadius: "var(--radius-card)",
    color: "#991B1B",
    display: "block",
    font: "500 0.875rem/1.45 var(--font-ui)",
    padding: "0.625rem 0.75rem",
    textAlign: "left",
  },
  footer: {
    alignItems: "center",
    background: "var(--white)",
    borderTop: "1px solid var(--border-subtle)",
    display: "flex",
    flex: "0 0 auto",
    flexWrap: "wrap",
    gap: "0.5rem",
    justifyContent: "center",
    marginTop: 0,
    paddingTop: "0.75rem",
    position: "static",
    zIndex: 2,
  },
  button(variant: "primary" | "secondary"): CSSProperties {
    return {
      alignItems: "center",
      backgroundColor: variant === "secondary" ? "var(--white)" : "var(--primary)",
      border: variant === "secondary" ? "1px solid var(--border-card)" : "1px solid var(--primary)",
      borderRadius: "var(--radius-control)",
      boxShadow: variant === "secondary" ? "none" : "var(--shadow-action)",
      color: variant === "secondary" ? "var(--title-ink)" : "var(--white)",
      cursor: "pointer",
      display: "inline-flex",
      fontWeight: 600,
      height: "2.75rem",
      justifyContent: "center",
      minWidth: "7rem",
      padding: ".5rem 1rem",
      position: "relative",
      scrollMarginBottom: "6rem",
      textAlign: "center",
      userSelect: "none",
      whiteSpace: "nowrap",
    };
  },
} satisfies Record<string, CSSProperties | ((...args: never[]) => CSSProperties)>;
