import type { CSSProperties } from "react";
import type { AuditGapView } from "../type/audit.types";

const gapMetaPalette: Record<string, string> = {
  header: "#0f172a",
  border: "#dbeafe",
  muted: "#64748b",
};

export const auditStyles = {
  root: {
    alignItems: "stretch",
    boxSizing: "border-box",
    color: "#0f172a",
    display: "flex",
    flexDirection: "column",
    fontFamily: "Arial, Helvetica, sans-serif",
    height: "100%",
    justifyContent: "flex-start",
    minHeight: 0,
    overflow: "hidden",
    position: "relative",
    textAlign: "left",
    width: "100%",
  } as CSSProperties,
  header: {
    boxSizing: "border-box",
    flex: "0 0 auto",
    padding: "0.85rem 1rem 0.6rem",
    position: "relative",
    textAlign: "left",
    width: "100%",
  } as CSSProperties,
  body: {
    boxSizing: "border-box",
    flex: "1 1 auto",
    minHeight: 0,
    overflowX: "hidden",
    overflowY: "auto",
    padding: "0 1rem 0.85rem",
    position: "relative",
    textAlign: "left",
    width: "100%",
  } as CSSProperties,
  summary: {
    display: "flex",
    flex: "0 0 auto",
    flexDirection: "column",
    marginLeft: 0,
    minWidth: "3.5rem",
  } as CSSProperties,
  summaryRow: {
    display: "flex",
    justifyContent: "flex-end",
    width: "100%",
  } as CSSProperties,
  summaryCosts: {
    color: "var(--background-main, #ffffff)",
    fontSize: "0.95rem",
    marginTop: "0.5rem",
  } as CSSProperties,
  summaryBadge: {
    alignItems: "center",
    boxSizing: "border-box",
    display: "flex",
    flexDirection: "column",
    gap: "0.1rem",
    justifyContent: "center",
    height: "4rem",
    marginLeft: "auto",
    padding: "0.35rem 0.5rem",
    whiteSpace: "nowrap",
    width: "max-content",
  } as CSSProperties,
  summaryBadgeCount: {
    color: gapMetaPalette.header,
    fontSize: "1.5rem",
    fontWeight: 700,
    lineHeight: 1,
    opacity: "0.8",
  } as CSSProperties,
  summaryBadgeLabel: {
    color: gapMetaPalette.muted,
    fontSize: "0.75rem",
    fontWeight: 300,
    opacity: "0.8",
  } as CSSProperties,
  panelHeader: {
    display: "grid",
    gap: "0.75rem",
    width: "100%",
  } as CSSProperties,
  headerTopRow: {
    alignItems: "flex-start",
    display: "flex",
    gap: "0.75rem",
    justifyContent: "space-between",
    minWidth: 0,
    width: "100%",
  } as CSSProperties,
  headerClose: {
    flex: "0 0 auto",
  } as CSSProperties,
  headerSpacer: {
    flex: "1 1 auto",
  } as CSSProperties,
  headerSummary: {
    display: "flex",
    justifyContent: "flex-start",
    width: "100%",
  } as CSSProperties,
  filters: {
    display: "flex",
    flex: "1 1 auto",
    flexDirection: "column",
    gap: "0.35rem",
    minWidth: 0,
  } as CSSProperties,
  filterRow: {
    alignItems: "flex-start",
    display: "flex",
    flexWrap: "wrap",
    gap: "0.75rem",
    width: "100%",
  } as CSSProperties,
  filterLabel: {
    display: "flex",
    flexDirection: "column",
    gap: "0.25rem",
    fontSize: "0.9rem",
    color: gapMetaPalette.muted,
  } as CSSProperties,
  filterSelect: {
    boxSizing: "border-box",
    border: `0.0625rem solid ${gapMetaPalette.border}`,
    borderRadius: "0.5rem",
    minWidth: "8rem",
    padding: "0.45rem 0.6rem",
    width: "100%",
  } as CSSProperties,
  filterSelectGroup: {
    flex: "1 1 10rem",
    minWidth: "10rem",
  } as CSSProperties,
  empty: {
    color: gapMetaPalette.muted,
  } as CSSProperties,
  sectionTitle: {
    color: gapMetaPalette.header,
    fontSize: "0.95rem",
    fontWeight: 700,
    margin: "0 0 0.35rem",
  } as CSSProperties,
  gaps: {
    boxSizing: "border-box",
    display: "flex",
    flexDirection: "column",
    gap: "0.9rem",
    marginTop: "0.45rem",
  } as CSSProperties,
  gapCard: {
    background: "#ffffff",
    border: `0.0625rem solid ${gapMetaPalette.border}`,
    borderRadius: "0.65rem",
    boxSizing: "border-box",
    display: "flex",
    flexDirection: "column",
    gap: "0.35rem",
    padding: "0.7rem 0.75rem",
  } as CSSProperties,
  gapHeader: {
    alignItems: "center",
    display: "flex",
    justifyContent: "space-between",
  } as CSSProperties,
  gapAspect: {
    color: gapMetaPalette.header,
    fontSize: "1rem",
    fontWeight: 700,
  } as CSSProperties,
  gapDate: {
    color: gapMetaPalette.muted,
    fontSize: "0.8rem",
  } as CSSProperties,
  gapMessage: {
    color: "#334155",
    fontSize: "0.92rem",
    lineHeight: 1.35,
    whiteSpace: "pre-wrap",
    wordBreak: "break-word",
  } as CSSProperties,
  gapProcess: {
    color: gapMetaPalette.muted,
    fontSize: "0.8rem",
    fontStyle: "italic",
  } as CSSProperties,
  toggle: {
    color: "#2563eb",
    cursor: "pointer",
    textDecoration: "underline",
  } as CSSProperties,
  noDialog: {
    boxShadow: "none",
  },
} satisfies Record<string, CSSProperties | ((...args: AuditGapView[]) => CSSProperties)>;
