import type { CSSProperties } from "react";

export const addIndexStyles = {
  root: {
    alignItems: "stretch",
    boxSizing: "border-box",
    color: "var(--text-main, #1f2937)",
    display: "flex",
    flexDirection: "column",
    gap: "1rem",
    height: "auto",
    justifyContent: "flex-start",
    margin: "0 auto",
    maxHeight: "100%",
    maxWidth: "42rem",
    minHeight: 0,
    padding: "1rem",
    width: "100%",
  },
  title: {
    color: "#0f172a",
    fontSize: "1.75rem",
    fontWeight: 700,
    lineHeight: 1.15,
    margin: 0,
  },
  fields: {
    display: "grid",
    gap: "0.75rem",
    margin: 0,
    padding: "0 1rem 1rem",
  },
  field: {
    background: "#ffffff",
    border: "0.0625rem solid rgba(15, 23, 42, 0.12)",
    borderRadius: "0.5rem",
    boxSizing: "border-box",
    display: "grid",
    gap: "0.55rem",
    margin: 0,
    padding: "0.6rem 0.75rem",
  },
  quoteField: {
    background: "#ffffff",
    border: "0.0625rem solid rgba(15, 23, 42, 0.12)",
    borderRadius: "0.5rem",
    boxSizing: "border-box",
    display: "grid",
    gap: "0.55rem",
    margin: 0,
    minInlineSize: 0,
    padding: "0.6rem 0.75rem",
  },
  legend: {
    color: "var(--text-main, #1f2937)",
    fontSize: "0.92rem",
    fontWeight: 700,
    margin: 0,
    padding: 0,
  },
  quoteControls: {
    display: "grid",
    gap: "0.65rem",
    margin: 0,
    padding: 0,
  },
  control: {
    display: "grid",
    gap: "0.35rem",
    margin: 0,
    padding: 0,
  },
  label: {
    color: "var(--text-main, #1f2937)",
    fontSize: "0.92rem",
    fontWeight: 700,
    margin: 0,
  },
  input: {
    background: "#ffffff",
    border: "1px solid rgba(71, 85, 105, 0.28)",
    borderRadius: "0.28rem",
    boxSizing: "border-box",
    color: "#0f172a",
    height: "1.8rem",
    minWidth: 0,
    padding: "0 0.5rem",
    width: "100%",
  },
  textArea: {
    background: "#ffffff",
    border: "1px solid rgba(71, 85, 105, 0.28)",
    borderRadius: "0.28rem",
    boxSizing: "border-box",
    color: "#0f172a",
    lineHeight: 1.4,
    minHeight: "3.6rem",
    minWidth: 0,
    padding: "0.5rem",
    resize: "vertical",
    width: "100%",
  },
  actions: {
    alignItems: "center",
    background: "#ffffff",
    borderTop: "1px solid rgba(0,0,0,0.08)",
    display: "flex",
    flex: "0 0 auto",
    flexWrap: "wrap",
    gap: "0.5rem",
    justifyContent: "center",
    marginTop: 0,
    paddingTop: "0.75rem",
    position: "static",
    zIndex: 2,
  },
  button(variant: "primary" | "secondary"): CSSProperties {
    return {
      alignItems: "center",
      backgroundColor: variant === "secondary" ? "var(--background-color-light, #fff)" : "var(--primary-color-light, #008ba3)",
      border: variant === "secondary" ? "1px solid rgba(0,0,0,0.12)" : "1px solid var(--primary-color-light, #008ba3)",
      borderRadius: "0.5rem",
      boxShadow: variant === "secondary" ? "0 0.05rem 0.15rem rgba(0,0,0,0.04)" : "0 0.1rem 0.25rem rgba(0,0,0,0.08)",
      color: variant === "secondary" ? "var(--text-main, #0f172a)" : "var(--background-color-light, #fff)",
      cursor: "pointer",
      display: "inline-flex",
      fontWeight: 600,
      height: "2.5rem",
      justifyContent: "center",
      minWidth: "7rem",
      outline: "none",
      padding: ".5rem 1rem",
      position: "relative",
      textAlign: "center",
      userSelect: "none",
      whiteSpace: "nowrap",
    };
  },
} satisfies Record<string, CSSProperties | ((variant: "primary" | "secondary") => CSSProperties)>;
