import type { CSSProperties } from "react";

export const addIndexStyles = {
  root: {
    alignItems: "stretch",
    boxSizing: "border-box",
    color: "var(--title-ink)",
    display: "flex",
    flexDirection: "column",
    gap: "0.75rem",
    height: "auto",
    justifyContent: "flex-start",
    minHeight: 0,
    width: "100%",
  },
  title: {
    color: "var(--title-ink)",
    fontSize: "var(--panel-title-size)",
    fontWeight: "var(--panel-title-weight)",
    letterSpacing: "var(--panel-title-tracking)",
    lineHeight: "var(--panel-title-line-height)",
    margin: 0,
  },
  fields: {
    display: "grid",
    gap: "0.75rem",
    margin: 0,
    padding: 0,
  },
  field: {
    background: "var(--white)",
    boxSizing: "border-box",
    display: "grid",
    gap: "0.55rem",
    margin: 0,
    padding: 0,
  },
  advanced: {
    background: "var(--white)",
    borderTop: "1px solid var(--border-card)",
    boxSizing: "border-box",
    overflow: "visible",
  },
  advancedTrigger: {
    alignItems: "center",
    background: "transparent",
    border: 0,
    color: "var(--title-ink)",
    cursor: "pointer",
    display: "grid",
    font: "inherit",
    fontWeight: 700,
    gridTemplateColumns: "1fr auto",
    minHeight: "2.75rem",
    padding: "0.5rem 0",
    textAlign: "left",
    width: "100%",
  },
  advancedContent: {
    display: "grid",
    gap: "0.5rem",
    padding: "0.35rem",
  },
  quoteField: {
    background: "var(--white)",
    border: 0,
    boxSizing: "border-box",
    display: "grid",
    gap: "0.55rem",
    margin: 0,
    minInlineSize: 0,
    padding: 0,
  },
  advancedRow: {
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) minmax(0, 7rem)",
    gap: "0.65rem",
    margin: 0,
    padding: 0,
  },
  control: {
    display: "grid",
    minWidth: 0,
    gap: "0.35rem",
    margin: 0,
    padding: 0,
  },
  label: {
    color: "var(--title-ink)",
    fontSize: "0.92rem",
    fontWeight: 700,
    margin: 0,
  },
  input: {
    background: "var(--white)",
    border: "1px solid var(--border-card)",
    borderRadius: "var(--radius-control)",
    boxSizing: "border-box",
    color: "var(--title-ink)",
    minHeight: "2.5rem",
    minWidth: 0,
    padding: "0 0.5rem",
    width: "100%",
  },
  textArea: {
    background: "var(--white)",
    border: "1px solid var(--border-card)",
    borderRadius: "var(--radius-control)",
    boxSizing: "border-box",
    color: "var(--title-ink)",
    lineHeight: 1.4,
    minHeight: "3.6rem",
    minWidth: 0,
    padding: "0.5rem",
    resize: "vertical",
    width: "100%",
  },
  actions: {
    alignItems: "center",
    background: "var(--white)",
    borderTop: "1px solid var(--border-subtle)",
    display: "flex",
    flex: "0 0 auto",
    flexWrap: "wrap",
    gap: "0.5rem",
    justifyContent: "center",
    marginTop: 0,
    paddingTop: "0.75rem",
    position: "static",
    zIndex: 2,
  },
  button(variant: "primary" | "secondary"): CSSProperties {
    return {
      alignItems: "center",
      backgroundColor: variant === "secondary" ? "var(--white)" : "var(--primary)",
      border: variant === "secondary" ? "1px solid var(--border-card)" : "1px solid var(--primary)",
      borderRadius: "var(--radius-control)",
      boxShadow: variant === "secondary" ? "none" : "var(--shadow-action)",
      color: variant === "secondary" ? "var(--title-ink)" : "var(--white)",
      cursor: "pointer",
      display: "inline-flex",
      fontWeight: 600,
      height: "2.75rem",
      justifyContent: "center",
      minWidth: "7rem",
      padding: ".5rem 1rem",
      position: "relative",
      textAlign: "center",
      userSelect: "none",
      whiteSpace: "nowrap",
    };
  },
} satisfies Record<string, CSSProperties | ((variant: "primary" | "secondary") => CSSProperties)>;
