import type { CSSProperties } from "react";

export const legalPlatDialogStyles = {
  header: {
    alignItems: "center",
    background: "#ffffff",
    borderBottom: "1px solid #d9e1ea",
    boxSizing: "border-box",
    display: "flex",
    flex: "1 1 auto",
    justifyContent: "space-between",
    minHeight: "2.2rem",
    minWidth: 0,
    padding: "0.35rem 0.75rem",
    width: "100%",
  },
  headerTitle: {
    color: "#0f172a",
    fontSize: "0.9rem",
    fontWeight: 600,
    lineHeight: 1.4,
  },
  dragHeader: {
    background: "#ffffff",
    border: "1px solid #d9e1ea",
    borderRadius: "0.25rem",
    boxSizing: "border-box",
    height: "0.72rem",
    width: "2.25rem",
  },
  content: {
    boxSizing: "border-box",
    display: "flex",
    flexDirection: "column",
    gap: "0.75rem",
    height: "100%",
    minHeight: 0,
    padding: "0.75rem",
    width: "100%",
  },
  plat: {
    alignItems: "center",
    display: "flex",
    flex: "1 1 auto",
    justifyContent: "center",
    minHeight: 0,
    overflow: "auto",
    width: "100%",
  },
} satisfies Record<string, CSSProperties>;
