import type { CSSProperties } from "react";

export const imageViewerStyles = {
  root: {
    display: "flex",
    flexDirection: "column",
    width: "100%",
    height: "100%",
    minHeight: 0,
    background: "#f8fafc",
    color: "#0f172a",
    boxSizing: "border-box",
  },
  topToolbar: {
    display: "grid",
    gridTemplateColumns: "auto minmax(12rem, 26rem)",
    alignItems: "center",
    justifyContent: "space-between",
    columnGap: "0.6rem",
    flex: "0 0 auto",
    minHeight: "2.6rem",
    padding: "0.3rem 0.55rem",
    borderBottom: "1px solid rgba(15, 23, 42, 0.12)",
    background: "#f8fafc",
    boxSizing: "border-box",
  },
  viewGroup: {
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-start",
    gap: "0.3rem",
    minWidth: 0,
  },
  footerToolbar: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "0.3rem",
    flex: "0 0 auto",
    minHeight: "2.35rem",
    padding: "0.25rem 0.55rem",
    borderTop: "1px solid rgba(15, 23, 42, 0.12)",
    background: "#f8fafc",
    boxSizing: "border-box",
  },
  icon: {
    display: "block",
    width: "1.15rem",
    height: "1.15rem",
    fill: "none",
    stroke: "currentColor",
    strokeLinecap: "round",
    strokeLinejoin: "round",
    strokeWidth: 1.7,
  },
  pageText: {
    minWidth: "6.2rem",
    fontSize: "0.82rem",
    fontWeight: 800,
    color: "#334155",
    textAlign: "center",
  },
  searchForm: {
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) auto auto",
    alignItems: "center",
    gap: "0.3rem",
    minWidth: 0,
  },
  searchInput: {
    width: "100%",
    minWidth: 0,
    height: "1.8rem",
    padding: "0 0.5rem",
    border: "1px solid rgba(71, 85, 105, 0.28)",
    borderRadius: "0.28rem",
    background: "#ffffff",
    color: "#0f172a",
    boxSizing: "border-box",
  },
  lensHost: {
    flex: "1 1 auto",
    width: "100%",
    height: "100%",
    minHeight: "12rem",
    background: "#fbfaf7",
  },
  overlay: {
    position: "absolute",
    inset: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    background: "#f8fafc",
  },
  body: {
    position: "relative",
    flex: "1 1 auto",
    display: "flex",
    minHeight: "18rem",
    overflow: "hidden",
  },
} satisfies Record<string, CSSProperties>;
